<a href="https://colab.research.google.com/github/SihomaSa/inmersion_datos_clases/blob/main/Min_Max.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [3]:
planet_density =np.array([5429,5243,5514,3934,1326,687,1270,1630,1850])

In [6]:
max_den=np.max(planet_density)
min_den=np.min(planet_density)

In [8]:
max_index=np.argmax(planet_density)
min_index=np.argmin(planet_density)
print(max_index)
print(min_index)

2
5


In [10]:
print(planet_density[min_index])
print(planet_density[max_index])

687
5514


In [13]:
planet_info = np.array([[5.2,9.6,19.2],[9.8,1.6,3.7]])
print(planet_info)
print('')
#compare all elements
print(np.min(planet_info))
#compare each column
print(np.min(planet_info,axis=0))
#compare each row
print(np.min(planet_info,axis=1))

[[ 5.2  9.6 19.2]
 [ 9.8  1.6  3.7]]

1.6
[5.2 1.6 3.7]
[5.2 1.6]


In [17]:
#compare all elements
print(np.max(planet_info))
#compare each column
print(np.max(planet_info,axis=0))
#compare each row
print(np.max(planet_info,axis=1))

19.2
[ 9.8  9.6 19.2]
[19.2  9.8]


In [18]:
#flatten matrix
print(planet_info)
print('')
arg_min=np.argmin(planet_info)
print(arg_min)

[[ 5.2  9.6 19.2]
 [ 9.8  1.6  3.7]]

4


In [19]:
np.unravel_index(arg_min, planet_info.shape)

(1, 1)

In [20]:
np.argmin(planet_info,axis=0)

array([0, 1, 1])

In [21]:
np.argmax(planet_info,axis=1)

array([2, 0])

In [23]:
#convert to tensor
p_den_tensor=torch.tensor(planet_density)
print(p_den_tensor)
print('')
#find min and max
print(torch.max(p_den_tensor))
print(torch.min(p_den_tensor))
print('')
#find index of min and max
print(torch.argmax(p_den_tensor))
print(torch.argmin(p_den_tensor))

tensor([5429, 5243, 5514, 3934, 1326,  687, 1270, 1630, 1850])

tensor(5514)
tensor(687)

tensor(2)
tensor(5)


In [25]:
#repeat with matrix
p_info_tensor=torch.tensor(planet_info)
print(p_info_tensor)
print('')
#compare all elements
print(torch.min(p_info_tensor))
print('')
#compare each column
print(torch.min(p_info_tensor, axis=0))
print('')
#compare each row
print(torch.min(p_info_tensor, axis=1))
print('')

tensor([[ 5.2000,  9.6000, 19.2000],
        [ 9.8000,  1.6000,  3.7000]], dtype=torch.float64)

tensor(1.6000, dtype=torch.float64)

torch.return_types.min(
values=tensor([5.2000, 1.6000, 3.7000], dtype=torch.float64),
indices=tensor([0, 1, 1]))

torch.return_types.min(
values=tensor([5.2000, 1.6000], dtype=torch.float64),
indices=tensor([0, 1]))

